name: add_tag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  add_tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: version frome branch name
        id: extract_version
        run: |
          MERGE_COMMIT=$(git log --merges -1 --pretty=format:"%s")
          echo "Merge commit message: $MERGE_COMMIT"
          VERSION=$(echo $MERGE_COMMIT | sed -n 's/Merge pull request .* from .*release\/ver\(.*\)/\1/p')
          echo "version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          if [ -z "$VERSION" ]; then
            echo "ERROR: No version extracted."
            exit 1
          fi

      - name: add tag
        if: steps.extract_version.outputs.VERSION != ''
        run: |
          git tag ver${{ steps.extract_version.outputs.VERSION }} $GITHUB_SHA
          git push origin ver${{ steps.extract_version.outputs.VERSION }}

