name: Create Pull Requests

on:
  push:
    branches:
      - 'release/**'

jobs:
  create-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"

          # Create Pull Request to develop
          gh pr create --head "$BRANCH_NAME" --base develop --title "Merge $BRANCH_NAME into develop" --body "This is an automated pull request to merge $BRANCH_NAME into develop."

          # Create Pull Request to main
          gh pr create --head "$BRANCH_NAME" --base main --title "Merge $BRANCH_NAME into main" --body "This is an automated pull request to merge $BRANCH_NAME into main."

